import React from 'react'

const Termandcondition = () => {
    return (
        <div className='w-[95%] m-auto mt-5 mb-28 sm:my-5'>
            <p>

                <h2 className="text-xl font-semibold mb-2">1. INTRODUCTION</h2>
                <p className="mb-4">
                    Thank you for using our platform (“Platform”) and Services (as defined below) through our mobile application and website (hereinafter referred to as the “App” or “Website”). Our platform is owned by Apex Inc. and operated through its subsidiary and APEX SUPPORT AND SERVICES (hereinafter referred collectively to as “APEX”) platform. These Terms of Service (hereinafter referred to as the “Agreement,” or “Terms”) apply to access and use of the software including but not limited to Mobile application, Web Application, and any other relevant medium. This Agreement is a legally binding agreement between you (hereinafter referred to as the “you”, “your”, User(s)”) and APEX and/or its subsidiaries and affiliates (together referred to as “we”, “us” or “our(s)”), governing the rights and obligations between you and APEX in respect of the Platform and Services.
                </p>
                <p className="mb-4">
                    By accessing and using our Platform, Website or App in any way, including, without limitation, browsing the Website, using any information, using any content, any services, etc., available therein, you agree to and are bound by these Terms of Service. If you do not accept these Terms of Service in full, please cease using our Platform, Website or App immediately, and contact us at <a href="mailto:support@apexin.in" className="text-blue-500">support@apexin.in</a>.
                </p>
                <p className="mb-4">
                    THESE PLATFORM TERMS HAVE BEEN DRAFTED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 (AS AMENDED) THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS OF SERVICE/ USER AGREEMENT FOR ACCESS OR USAGE OF THE APP AND RELATED SERVICES.
                </p>
                <p className="mb-4">
                THESE TERMS AND THE PLATFORM PRIVACY POLICY ARE COMPLIANT WITH INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OR INFORMATION) RULES, 2011 (AS AMENDED) WHEREVER APPLICABLE IN ANY MANNER.
                </p>
                <p className="mb-4">
                    PLEASE READ THE TERMS CONTAINED IN THIS AGREEMENT CAREFULLY TO ENSURE THAT YOU UNDERSTAND EACH PROVISION.
                </p>
                <p className="mb-4">
                    BY USING THE PLATFORM BY DOWNLOADING AND INSTALLING THE APP YOU ACCEPT THIS AGREEMENT AND AGREE THAT (A) YOU HAVE READ AND UNDERSTOOD THE AGREEMENT; AND (B) YOU ACCEPT THIS AGREEMENT AND AGREE THAT YOU ARE LEGALLY BOUND BY ITS TERMS AND THE PLATFORM PRIVACY POLICY, REFERENCED HEREIN.
                </p>
                <p className="mb-4">
                    You represent and warrant to us that you will use the Platform in a manner consistent with all Applicable Laws, as defined in Section 2. We reserve the right to refuse access to use the Platform or to terminate access granted to existing Users at any time without according any reasons for doing so.
                </p>

                <h2 className="text-xl font-semibold mb-2">2. DEFINITIONS</h2>
                <p className="mb-4">
                    In this Agreement, unless otherwise provided, the following words shall mean:
                </p>
                <p className="mb-4">
                    “Applicable Laws” means any applicable Indian statutes, laws, ordinances, regulations, rules, orders, by-laws, administrative interpretation, writ, injunction, directive, judgment or decree or other instruments which has a force of law in India, as is in force from time to time;
                </p>
                <p className="mb-4">
                    “Confidential Data” means any information related to the User, which the User shares with APEX or submits on the App and/or Website and the proprietary information relation to APEX or which the User may have come into possession of or pursuant to this Agreement;
                </p>

                <h2 className="text-xl font-semibold mb-2">3. THE PLATFORM AND SERVICES</h2>
                <p className="mb-4">
                    APEX, through its Platform, allows agents to sell various financial and non-financial products and services such as Demat account, credit, loans, saving accounts, etc. to their clients (“User-Clients”), and allows Users to manage money through our Platform (“Services”). All results generated by the Platform is made available on as-is and available basis based on the information you provide us.
                </p>

                <h2 className="text-xl font-semibold mb-2">4. TERRITORY</h2>
                <p className="mb-4">
                    Platform, Website, and the App are only available for use and download within the territory of India. If you have any questions regarding this Section, please email us at <a href="mailto:support@apexin.in" className="text-blue-500">support@apexin.in</a>.
                </p>

                <h2 className="text-xl font-semibold mb-2">5. PRIVACY POLICY</h2>
                <p className="mb-4">
                    Our Privacy Policy describes how we handle the personal and business information (collectively “Personal Information”) you provide to us when you use or register on the Platform, the Website or the App. You understand that through your use of our Platform, Website, or the App, you consent to the collection, processing, and use (as set forth in the Privacy Policy) of this information.
                </p>
                <p className="mb-4">
                    Upon your written request, APEX will provide you with a list of all personal information that we store concerning you within sixty (60) days of receiving your request. Also, upon your prior written request, APEX will delete any such information within sixty (60) days of receiving your request. Notwithstanding this, APEX can deny such requests, reasonably and in its sole discretion if it suspects fraud, misinformation or in any other situation permitted by law. Further, notwithstanding this if you ask APEX to delete all such information, we will not be able to continue to provide the access to the Website, App or Platform to you.
                </p>

                <h2 className="text-xl font-semibold mb-2">6. ELIGIBILITY & ACCESS RESTRICTIONS</h2>
                <p className="mb-4">
                    To be eligible to use our Platform, Website, or the App, you must meet the following criteria and represent and warrant that you:
                </p>
                <ul className="list-disc list-inside mb-4">
                    <li>(1) are not currently restricted from accessing our Platform, Website, or the App, or not otherwise prohibited from having an account,</li>
                    <li>(2) are not our competitor, or are not using our Platform, Website, or the App for reasons that are in competition with us;</li>
                    <li>(3) have full power and authority to enter into this Agreement and doing so will not violate any other agreement to which you are a party;</li>
                    <li>(4) will not violate any of our rights, including intellectual property rights such as patent, copyright, and trademark rights; and</li>
                    <li>(5) agree to provide at your cost all equipment, browser software, and internet access necessary to use our Platform, Website, or the App.</li>
                </ul>

                <h2 className="text-xl font-semibold mb-2">7. REGISTRATION ON OUR PLATFORM</h2>
                <p className="mb-4">
                    You can access and use the Platform via <br />(i) the App which can be downloaded and installed from the Google Play Store <br />(ii) the Website at <a href="https://www.apexin.in" className="text-blue-500">https://www.apexin.in</a>.
                </p>

                <h2 className="text-xl font-semibold mb-2">7. REGISTRATION ON OUR PLATFORM</h2>
                <p className="mb-4">
                    By registering on our Platform, you understand that:
                </p>
                <p className="mb-4">
                    At the time of registration, you may be required to complete a verification process (“Verification”) as part of setting up your User account, as applicable that would enable you to use the Platform and access our Services (“Account”). Once you have successfully completed the Verification, as applicable, and have set up your Account, you will be given a username and your mobile number will be registered with the Platform using a One-time-Password (“OTP”) (together hereinafter referred to as “Access Credentials”). You are responsible for maintaining the confidentiality of your Access Credentials and are fully responsible for all activities that occur through your Account. Should there be instances of any unauthorized use of your Account or Access Credentials or any other breach of security, you are required to notify APEX to stop processing requests from your Account, until further instructions.
                </p>
                <p className="mb-4">
                    During the registration process, you may be asked to provide APEX with yours and/or your User-Client’s mobile numbers, email, and any other information reasonably required to allow APEX or its subsidiaries, third-party partners or financial institutions (“Brand Partners”) to provide you with Services through our Platform.
                </p>
                <p className="mb-4">
                    By registering yours or your User-Client's phone numbers with APEX, you consent to be contacted by APEX via phone calls, WhatsApp, SMS notifications or instant messages, in case of verifications and in case of subscription/service/promotional updates. You may opt out of subscription/service/promotional updates upon following due procedure as highlighted by the support personnel over authorized channels.
                </p>
                <p className="mb-4">
                    If you provide APEX with your User-Client’s mobile number, email id or any other information, you certify and represent that you have their consent and permission to do so under all applicable laws. You further indemnify APEX from any claims, actions or liabilities arising from your breach of this Section 7.
                </p>
                <p className="mb-4">
                    It is your responsibility to provide a correct mobile number, and email id for yourself and your User-Clients so that APEX can communicate with you via various communication channels. You understand and agree that if APEX sends a communication to you but you do not receive it because you have provided a mobile number that is incorrect, out of date or blocked or because you, or your User-Client, are otherwise unable to receive SMS, APEX shall be deemed to have provided the communication effectively.
                </p>

                <h2 className="text-xl font-semibold mb-2">8. USING THE PLATFORM</h2>
                <p className="mb-4">
                    By visiting our website or mobile application, and accessing the information, resources, services, products, and tools we provide for you, either directly or indirectly (hereafter referred to as “Resources”), you agree to use these Resources only for the purposes intended as permitted by this Agreement, and/or Applicable Laws.
                </p>
                <p className="mb-4">
                    Wherein, you understand that:
                </p>
                <p className="mb-4">
                    In order to access our Resources, you may be required to provide certain accurate, corrected and updated information about yourself as stated and described in our Privacy Policy. Accessing (or attempting to access) any of our Resources by any means other than through the means we provide is strictly prohibited. You specifically agree not to access (or attempt to access) any of our Resources through any automated, unethical or unconventional means. Engaging in any activity that disrupts or interferes with our Resources, including the servers and/or networks to which our Resources are located or connected, is strictly prohibited.
                </p>

                <h2 className="text-xl font-semibold mb-2">9. ACCESS TO PLATFORM, ACCESS RIGHTS AND RESTRICTIONS</h2>
                <p className="mb-4">
                    Subject to your compliance with the terms of this Agreement, we grant you a limited, non-exclusive, revocable, non-transferable, non-licensable, non-sublicensable right to access and use our Platform, Website, and App strictly in accordance with this Agreement.
                </p>
                <p className="mb-4">
                    You will not use, copy, adapt, modify, prepare derivative works based upon our Platform, Website, or the App, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit our Platform, Website, or the App, except as expressly permitted in these Terms. When accessing our Platform, Website, or the App, you need to make sure that your internet connection is adequate. You are solely responsible for your internet connection including and not limited to the applicable charges, rates, tariffs, and other fees that might apply.
                </p>
                <p className="mb-4">
                    YOU AGREE WE ARE NOT LIABLE FOR ANY DAMAGES OR INJURY RESULTING FROM YOUR ACCESS OR USE OF OUR PLATFORM, WEBSITE, OR THE APP. WE PROVIDE NO WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE OR WARRANTY OF MERCHANTABILITY. THERE IS NO WARRANTY WHICH WILL EXTEND BEYOND THE DESCRIPTION ON THE FACE HEREOF. ANY DAMAGE ALLEGED FOR A LOSS OR INJURY IS LIMITED TO THE FEE, IF ANY, PAID TO APEX FOR THE ABILITY TO ACCESS OR USE OUR PLATFORM, WEBSITE, AND/OR THE APP.
                </p>


                <h2 className="text-xl font-semibold mb-4">10. USER DECLARATION</h2>
                <p className="mb-4">
                    You agree, acknowledge and declare that:
                </p>
                <ul className="list-disc list-inside mb-4">
                    <li>you are availing the Services offered on the Platform out of your free will and volition;</li>
                    <li>the amounts invested on the Platform are through legitimate and bonafide sources only and does not involve and is not designed for the purpose of contravention or evasion of any Applicable Laws;</li>
                    <li>you shall review and comply with notices sent by APEX, if any, concerning the Platform and Services;</li>
                    <li>you shall review the Platform’s Privacy Policy, regularly as may be amended;</li>
                </ul>

                <h2 className="text-xl font-semibold mb-4">11. RESERVATION OF RIGHTS AND USER CONDUCT</h2>
                <p className="mb-4">
                    You acknowledge and agree that the Platform is provided for your use. Except to the extent necessary to access and use the Platform, nothing in this Agreement grants any title or ownership interest in or to any copyrights, patents, trademarks, trade secrets or other proprietary rights in or relating to the App/Website and the Platform whether expressly, by implication, by estoppel, or otherwise. APEX, its licensors, partners, and service providers reserve and will retain its entire right, title, and interest in and to the content on the Platform including all copyrights, trademarks, and other intellectual property rights therein or relating thereto, except as expressly granted to you in this Agreement.
                </p>
                <p className="mb-4">
                    You may only access and use APEX for lawful purposes only. You are responsible for adhering to any and all laws, rules, and regulations that are applicable regardless of any previous knowledge or lack of knowledge about such laws, rules or regulations.
                </p>
                <p className="mb-4">
                    Any content uploaded by APEX on the application and website is for guidance and education purposes only. APEX does not hold any liability on the accuracy of the content provided. You are responsible to verify each content before sharing, or modifying it.
                </p>
                <p className="mb-4">
                    APEX’s rights and protections as stated in these Terms are equally applicable to any internet service provider that it has selected to host APEX or any related resources.
                </p>
                <p className="mb-4">
                    You expressly agree not to:
                </p>
                <ul className="list-disc list-inside mb-4">
                    <li>duplicate, copy, adapt, modify, prepare derivative works based on the Platform to license, sublicense, publish, broadcast, transmit, distribute, perform, display, sell, rebrand, otherwise transfer or commercially exploit the Platform (excluding any User content);</li>
                    <li>reverse engineer, download, decompile, disassemble, decipher, capture screen shots, or otherwise attempt to derive the source code for any underlying intellectual property used to provide the Platform or any part thereof;</li>
                    <li>commit or cause to be committed any criminal offense or encourage conduct that would constitute a criminal offense or give rise to a civil liability, or otherwise violate any local, state, federal or international law or regulation;</li>
                    <li>upload, post, e-mail or otherwise transmit any content that is unlawful, defamatory, harassing, abusive, invasive of another’s privacy, infringes upon the rights of third parties, harmful, wrongful, or obscene;</li>
                    <li>harm any minors in any way;</li>
                    <li>upload, post, e-mail or otherwise transmit any material, information or content that you do not have a right to transmit under law or contractual relationship;</li>
                    <li>upload, post, email or otherwise transmit any material, information or content that infringes any patent, trademark, trade secret, copyright, or other proprietary rights of any other individual, party or entity.</li>
                    <li>disguise the origin of the material, information or content by omitting or obscuring copyright or authorship, or by forging headers or otherwise manipulating identifiers;</li>
                    <li>upload, post, e-mail or otherwise transmit any unsolicited advertising, promotional materials, or other forms of solicitation, such as “junk mail”, “spam”, “chain letters”, or “pyramid schemes”;</li>
                    <li>upload, post, e-mail or otherwise transmit any material, information or content that contains software virus or any other computer code, file or program that would interfere with the functionality of any computer software, hardware or telecommunication equipment.</li>
                    <li>disrupt the normal communication or otherwise act in such a way that would negatively impact other users’ ability to engage in real-time exchanges;</li>
                    <li>impersonate or claim a relationship with or speak for any individual, business, association, institution, or other organization, including, but not limited to APEX for which you have no authorization to do so or to claim such a relationship;</li>
                    <li>interfere with or disrupt the services or servers or networks connected to the services, or disobey any requirements, procedures, policies, or regulations of networks connected to the services and/or this website.</li>
                    <li>collect or store personal data about other users or User-Clients in a manner incompatible with Applicable Laws;</li>
                    <li>stalk or otherwise harass any individual;</li>
                    <li>utilize information, content or any data you view on and/or obtain from the Platform to provide any service that is competitive with us;</li>
                    <li>rent, lease, loan, trade, sell/re-sell access to the Platform or any information therein, or the equivalent, in whole or part;</li>
                    <li>use malware or any other means that impair optimal functioning of the App and/or Website;</li>
                    <li>engage in “framing”, “mirroring”, or otherwise simulating the appearance or function of the Website or App;</li>
                    <li>attempt to or actually override any security component included in or underlying the App and/or the Platform;</li>
                    <li>engage in any action that interferes with the proper working of or places an unreasonable load on our infrastructure, including but not limited to unsolicited communications, attempts to gain unauthorized access, or transmission or activation of computer viruses;</li>
                    <li>remove any copyright, trademark or other proprietary rights notices contained in or on the App and on the Platform including those of both APEX or any of our partners;</li>
                    <li>use any information obtained from the App and/or the Platform to harass, abuse or harm another User;</li>
                    <li>violate the provisions of the Information Technology Act, 2000 and rules and regulations thereunder (as updated) and any applicable data protection laws;</li>
                    <li>host, display, upload, modify, publish, transmit, update or share any information that is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever, or infringes any patent, trademark, copyright or other proprietary rights of a third-party or impersonates another person or threatens public health or safety; promotion of cigarettes or any other tobacco products or consumption of intoxicant including alcohol or threatens critical information infrastructure.</li>
                    <li>post anything on social media which is detrimental to the reputation of the platform APEX or to its partner brands. In case any violation is found your account will be blocked and earnings frozen.</li>
                </ul>
                <h2 className="text-xl font-semibold mb-4">12. USER GENERATED CONTENT</h2>
                <p className="mb-4">
                    We may provide various open communication tools on our website, such as blog comments, posts, photos, videos, courses, public chat, forums, message boards, newsgroups, reviews, various social media services, etc. You understand that we do not pre-screen content posted by users of these various communication tools, which means that if you choose to use these tools to submit any type of content to our website (“User Generated Content”), then it is your personal responsibility to use these tools in a responsible and ethical manner. By posting information or otherwise using any open communication tools as mentioned, you agree that you will not upload, post, share, or otherwise distribute any content that upload, post, share, or otherwise distribute any content that.
                </p>

                <h2 className="text-xl font-semibold mb-4">13. OWNERSHIP, PROPRIETORY INFORMATION AND INTELLECTUAL PROPERTY RIGHTS</h2>
                <p className="mb-4">
                    You agree that the Platform including the graphics, our trademarks and editorial content contains proprietary content, information, and material, which are owned by APEX and/or our licensors, including our customers, brands and agencies and partners, and are protected by applicable intellectual property and other laws, including but not limited to copyright.
                </p>
                <p className="mb-4">
                    All content and materials available on APEX, including but not limited to text, graphics, website name, code, images and logos are either the intellectual property of APEX or under licensed use by Vitrak, and are protected. Any inappropriate, unauthorized, or prohibited use, including but not limited to the reproduction, distribution, display or transmission of any content on this site is strictly prohibited, unless specifically authorized.
                </p>

                <h2 className="text-xl font-semibold mb-4">14. CONTRIBUTIONS TO APEX</h2>
                <p className="mb-4">
                    By submitting ideas, suggestions, documents, and/or proposals (“Contributions”) to APEX through its suggestion or feedback webpages, you acknowledge and agree that:
                </p>
                <ul className="list-disc list-inside mb-4">
                    <li>Your Contributions do not contain confidential or proprietary information.</li>
                    <li>APEX is not under any obligation of confidentiality, express or implied, with respect to the Contributions.</li>
                    <li>APEX shall be entitled to use or disclose (or choose not to use or disclose) such Contributions for any purpose, in any way, in any media worldwide.</li>
                    <li>APEX may have something similar to the Contributions already under consideration or in development.</li>
                    <li>Your Contributions automatically become the property of APEX without any obligation of APEX to you.</li>
                    <li>You are not entitled to any compensation or reimbursement of any kind from APEX under any circumstances.</li>
                </ul>

                <h2 className="text-xl font-semibold mb-4">15. INDEMNITY</h2>
                <p className="mb-4">
                    Users agree to indemnify and hold APEX, its parent company, officers, subsidiaries, affiliates, successors, assigns, directors, officers, agents, service providers, suppliers, and employees (“Indemnitees”) harmless from any claim or demand, including penalty, reasonable attorney fees, and court costs, made by any third party due to or arising out of (i) content submitted by the User, (ii) Users’ use of the service, (iii) violation of the Terms of Service or Privacy Policy, (iv) breach by the User of any of the Terms, representations, and warranties herein, (v) the negligence, fraud, or willful misconduct of User, User’s agents, or contractors; (vi) incorrect information provided by User in User’s Account or elsewhere; or (vii) a failure by User or User’s agents, contractors, or invitees to comply with applicable laws and regulations.
                </p>

                <h2 className="text-xl font-semibold mb-4">16. NO RESALE OF SERVICE</h2>
                <p className="mb-4">
                    Under no condition should you collect any money or benefit from any person, including a User-Client, on the pretext of providing services through the Resources or using the name of APEX or its affiliates, partners, advisors, directors, or employees. In case of breach of trust, you will be liable to return such money to such person or User-Client immediately, and indemnify APEX. APEX shall have the right to disable your Account with immediate effect.
                </p>

                <h2 className="text-xl font-semibold mb-4">17. DEALINGS WITH THIRD PARTIES</h2>
                <p className="mb-4">
                    The Platform may also include access to products and services of independent third parties either directly or via links to sites operated by such third parties. Where these products and services of third parties form part of the Platform, we will endeavor, but are not obliged to, indicate that these products and services are provided by third parties. In all cases, your correspondence or business dealings with, or participation in promotions of, other parties found on or through the Platform (including without limitation providers of products and services, advertisers, and other users of the Platform), including payment and delivery of related goods or services, and any other terms, conditions, warranties, or representations associated with such dealings, are solely between you and such third party, even where it is in relation to any products or services that are co-branded with us, which may include our trademarks. You agree that we shall not be responsible or liable in any way for any loss or damage of any sort incurred as the result of any such dealings with any third parties, as the result of the presence of such third parties on the Platform, or as the result of the use of the Service in any way by such third parties.
                </p>

                <h2 className="text-xl font-semibold mb-4">18. LINKS</h2>
                <p className="mb-4">
                    The Platform may provide, or third parties may provide, links to other World Wide Web or other online electronic sites or resources. You acknowledge that APEX has no control over such sites and resources; you acknowledge and agree that APEX is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that APEX shall not be responsible or liable, in any manner whatsoever, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such goods or services available on or through any such site or resource.
                </p>

                <h2 className="text-xl font-semibold mb-4">19. PAYMENT</h2>
                <p className="mb-4">
                    <strong>Access to Platform:</strong> Access to our Platform and Services are currently provided to you at no cost to you. In the event that we change this in the future, we will communicate such modification to you.
                </p>
                <p className="mb-4">
                    <strong>Payment for Content:</strong> Notwithstanding anything to the contrary herein, you will be responsible for paying the Fees for the Content offered on our Platform offered by our Brand Partners. By purchasing any Content offered on the Platform, you are granted a non-exclusive and non-transferable right to access, view and use the relevant Content and may not use or reproduce any of the Content in any manner, unless expressly authorised by APEX. For the purposes of these Terms of Service, “Content” shall mean any content, courses, instruction, or other material made available to you over our Platform by APEX or a Content Partner. For the purposes of these Terms of Service, a “Content Partner” shall mean any entity authorized by APEX to make Content available to Users over the Platform. You may pay for the Content on our App by using any legally valid method of payment as accepted by the Platform.
                </p>

                <h2 className="text-xl font-semibold mb-4">20. USER EARNINGS</h2>
                <p className="mb-4">
                    <strong>Commissions:</strong> Users can earn commissions on our App (“User Earnings”) by providing to their User-Clients, through our App or Platform, services affiliated to or authorized by our Brand Partners. User Earnings shall be reflected and credited to the User’s Account on the App once APEX receives verified updates (“Update(s)”) from our Brand Partners or financial institutions to credit such User Earnings to a User’s Account on the App. If APEX doesn’t receive the Update from the Brand Partners, it shall not update User Earnings. Under no circumstances can APEX be held liable for any deficiency in the User Earnings or the non-payment thereof if such a claim arises from the non-receipt of an Update as required by APEX.
                </p>
                <p className="mb-4">
                    <strong>Transfer of User Earnings:</strong> Users must register a bank account on the App or Platform and provide valid bank account and KYC details to be eligible to transfer their User Earnings to such bank accounts. Users can transfer all their accumulated User Earnings, in whole or in parts, to their registered bank account by clicking on the “Transfer Now” button on User’s Account on the App (“Transfer Request”). The transfer of User Earnings to the registered bank account of the User shall happen within 24-48 hours of the request.
                </p>
                <p className="mb-4">
                    <strong>Failed Transfer Request:</strong> Any Transfer Request that has been initiated by a User, who has not registered a bank account with the App or Platform or has provided invalid bank account details and KYC details or has not updated their valid bank account details on the Platform or App, shall automatically fail.
                </p>
                <p className="mb-4">
                    <strong>Limitations:</strong> A User must initiate a Transfer Request to a valid and registered bank account no later than three (3) months from when that User Earning was updated or credited to their User Account on the App. Any User Earnings, for which either no Transfer Request has been initiated or there have been no valid bank or KYC details shared with the Platform for a period exceeding three (3) months, shall be deemed “Unused Earnings.” All Unused Earnings are subject to being rolled back or debited from the User’s Account on the App at the sole discretion of APEX.
                </p>


                <h2 className="text-xl font-semibold mb-4">21. TRAINING</h2>
                <p className="mb-4">
                    Watching training videos (webinars, courses) will fetch the Apex Partner ‘x’ Automatic Sale Redemption.
                </p>
                <p className="mb-4">
                    APEX from time to time can give extra Rewards on different activities, details of which would be available on the Apex application under the “Rewards” section.
                </p>
                <p className="mb-4">
                    APEX reserves the right, at its sole discretion, to change the Rewards and modify any terms, features, or discontinue the Rewards Program without any prior written notice. Please refer to your APEX android application, section “Rewards” to review the latest Reward/Loyalty Program.
                </p>
                <p className="mb-4">
                    APEX reserves the right to suspend any account and claw back all past, current, and future earnings from APEX in case of willful misconduct, gross negligence, indecent behavior, customer complaint, charging money from customers, indecent behavior towards any APEX employee, contractor or sub-contractor, any other fraud or potential fraud by the agent.
                </p>

                <h2 className="text-xl font-semibold mb-4">22. TERMINATION</h2>
                <p className="mb-4">
                    We reserve the right to suspend or terminate your account or cease providing you with access to all or part of our Platform, Website, or the App if we reasonably believe: (i) you have violated this Agreement and/or our Privacy Policy; (ii) you create risk or possible legal exposure for APEX; (iii) our provision of our Platform, Website, or the App to you is no longer commercially viable; (iv) there is a breach of security or misuse of the account by you; (v) if any information provided during the registration or Verification process or thereafter proves to be inaccurate, not current or incomplete; (vi) if, in APEX’s assessment, you have committed any kind of fraud including but not limited to forged documents, identity fraud, willful misconduct, or any other such behavior as noticed by APEX; (vii) if, in APEX’s assessment, you have engaged in actions that are fraudulent, negligent or derogatory to APEX’s interests; (viii) or if in APEX’s assessment, you have taken money from or shared information and/or data of User-Clients without their consent or knowledge; (ix) you mis-sell or attempt to mis-sell your services under the name and banner of APEX; or (x) you have attempted to harm the goodwill of the company directly or indirectly, or you have posted any false or incorrect escalation on social media or any other public platform, even if the company believes that the escalation is false or incorrect.
                </p>
                <p className="mb-4">
                    We will make reasonable efforts to notify you of such termination by the mobile number and email address associated with your account or the next time you attempt to access your account, depending on the circumstances. In all such cases, in APEX’s sole discretion, APEX may (i) terminate Agreement; (ii) limit or completely disable your license to use or access our Platform, Website, or the App; (iii) penalize you in a manner consistent with this Agreement and all applicable laws; (iv) freeze and reverse any past earnings you may have had using the Platform; or (v) all of the above.
                </p>

                <h2 className="text-xl font-semibold mb-4">23. LIMITATION OF WARRANTIES</h2>
                <p className="mb-4">
                    By using our website, you understand and agree that all Resources we provide are “AS IS” and “AS AVAILABLE”. We do not represent or warrant to you that: (i) the use of our Resources will meet your needs or requirements, (ii) the use of our Resources will be uninterrupted, timely, secure or free from errors or viruses, (iii) the information obtained by using our Resources will be accurate or reliable, (iv) any downloads from APEX will not harm your computer or device in any way, and (v) we have screened or verified any of the information posted herein, unless otherwise specifically so stated on the Website. To the maximum extent permitted by law, APEX has no liability in relation to or arising out of the Website Information and recommendations. You are responsible for the final choice of your product. Please seek further advice from APEX or the relevant participating companies before choosing any product or service which you wish to avail of if you have any doubts or queries about the same. APEX does not guarantee when or if you will actually acquire the product that you have chosen and does not accept any liability arising out of delay in you acquiring the product you have chosen. You acknowledge and accept that the final issuance of the product is subject to the underwriting norms and sole discretion of the company whose product you have chosen to buy. WE DISCLAIM ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. No advice or information, whether oral or written, obtained from us or through our Platform, Website, or the App, will create any warranty or representation not expressly made herein.
                </p>

                <h2 className="text-xl font-semibold mb-4">24. LIMITATION OF LIABILITY</h2>
                <p className="mb-4">
                    You expressly understand and agree that in no event APEX or its contractors, agents, licensors, partners, employees, representatives, suppliers be liable to you for any special, direct, indirect, incidental, consequential, punitive, or exemplary damages (including without limitation loss of business opportunities, lost revenues, or loss of anticipated profits or any other pecuniary or non-pecuniary loss or damage of any nature whatsoever) arising out of or relating to this agreement, or which may be incurred by you as a result of using our website or its resources or the content, the services, or any reference site, or your use or inability to use the services. In any event, APEX or any of its contractors, directors, employees, agents, third-party partners, licensors or suppliers shall not be liable for any or all damages, liabilities, losses, costs or consequences thereof arising out of or in relation to usage/Agreement, or the Products or Services, however caused and whether arising in contract, tort including negligence, warranty or otherwise. Any claim against us shall be limited to the amount you paid to APEX, if any.
                </p>

                <h2 className="text-xl font-semibold mb-4">25. GOVERNING LAW</h2>
                <p className="mb-4">
                    This Agreement and the Privacy Policy shall be governed and construed in accordance with the laws of the Republic of India and the courts at New Delhi, India shall have exclusive jurisdiction on all matters and disputes arising out of and relating to the Platform, Website, App or Services provided therein for any actions not subject to Dispute Resolution and Arbitration provisions as set forth in Section 25.
                </p>

                <h2 className="text-xl font-semibold mb-4">26. DISPUTE RESOLUTION AND ARBITRATION</h2>
                <p>
                    Any claim, dispute or difference relating to or arising out of these Terms, and Privacy Policy shall be referred to the arbitration, of a sole arbitrator appointed mutually. The arbitration shall be subject to the Arbitration and Conciliation Act, 1996 as may be amended from time to time. The seat and venue of arbitration shall be New Delhi, India. The proceedings shall be undertaken in English. The arbitration award shall be final and binding on the parties.
                </p>

                <h2 className="text-xl font-semibold mb-4">27. RELATIONSHIP OF PARTIES</h2>
                <p>
                    The parties hereto are independent contractors, and nothing contained herein shall be interpreted as creating any relationship other than that of independent contracting parties. The parties shall not be construed as being partners, joint ventures, shareholders, employer/employee, or agent/servant. The User has no power or authority to bind APEX to any obligation, agreement, debt or liability. The User shall not hold itself out as an agent or representative of APEX.
                </p>

                <h2 className="text-xl font-semibold mb-4">28. REFERRAL POLICY</h2>
                <p>
                    This referral program replaces all previous referral programs effective 1 Nov 2024. Incentives in this program apply to all referring GPs, irrespective of previous program participation. For example, if your referral who joined up to 30 days prior to launch of this program completes their first sale after the launch (within 30 days of joining), then you will still receive a locked reward of Rs 500.
                </p>
                <p>
                    Referral policy is not valid in cases where the referral is made to an immediate family member. This means that if an immediate family member has been referred, the respective APEX Partner will not be entitled to any referral reward or referral lifetime commission income.
                </p>
                <p>
                    Insurance sales done by your referral will not be considered towards any referral reward/incentive.
                </p>
                <p>
                    APEX reserves the right, at its sole discretion, to change the amount of the referral award and modify any terms, features, or discontinue the program without any prior written notice. Please refer to your APEX Android application, section “Refer and Earn” to review the latest incentive policy.
                </p>
                <p>
                    APEX reserves the right to suspend your account and claw back all your past, current, and future earnings from GroMo in case of willful misconduct, gross negligence, indecent behavior, customer complaints, or other fraud by the agent.
                </p>

                <h2 className="text-xl font-semibold mb-4">29. MODIFICATIONS</h2>
                <p>
                    We reserve the right, at our sole discretion, to change or modify this Agreement at any time. In the event we modify the terms of this Agreement, such modifications shall be binding on you only upon your acceptance of the modified Agreement. We will inform you about the modifications via email, on the Platform, Website, and the App by posting a modified version of this page, or by a comparable means within a reasonable time period. Your continued use of the Platform, Website, or the App shall constitute your consent to such changes.
                </p>

                <h2 className="text-xl font-semibold mb-4">30. Grievance Redressal Mechanism</h2>
                <p>
                    <strong>APEX SUPPORT AND SERVICES (APEX)</strong>
                </p>
                <p>
                    (a) <strong>Where can a complaint be made?</strong><br />
                    Any customer having a grievance/complaint/feedback with respect to the services offered by Apex support and services may write to Apex’s Customer Service Department through any of the following channels:
                </p>
                <ul className="list-disc ml-6">
                    <li>Call at <span className=' font-medium'>+91 7042336564</span></li>
                    <li>Email - <span className=' text-blue-800'>support@apexin.in</span></li>
                    <li>Correspondence Address - D35 Noida sector 2 near Red FM building 201301</li>
                    <li>Website - www.apexin.in</li>
                </ul>
                <p>
                    (b) <strong>Whom to approach for redressal?</strong><br />
                    Customers are requested to raise their concerns through any of the channels mentioned above, the acknowledgment of which is sent within 3 working days. The issue is generally resolved within 7-10 working days of raising the concern. In case the same is not resolved or if the customer is not satisfied with the resolution, it may be raised to the Grievance Redressal Officer.
                </p>
            </p>
        </div>
    )
}

export default Termandcondition


